# Generated by Django 6.0 on 2025-12-20 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titulo del artículo', max_length=200)),
                ('slug', models.SlugField(help_text='Slug único para la URL del artículo', max_length=200, unique=True)),
                ('content', models.TextField(help_text='Contenido del artículo en formato Markdown')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('editing', 'Editing')], default='draft', help_text='Estado del artículo', max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del artículo')),
                ('publication_date', models.DateTimeField(blank=True, help_text='Fecha de publicación del artículo', null=True)),
                ('author', models.ForeignKey(blank=True, help_text='Autor del artículo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
