# Generated by Django 6.0 on 2026-01-08 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Contenido del comentario en formato Markdown')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('editing', 'Editing')], default='draft', help_text='Estado del comentario', max_length=50)),
                ('publication_date', models.DateTimeField(blank=True, help_text='Fecha de publicación del comentario', null=True)),
                ('author', models.ForeignKey(blank=True, help_text='Autor del comentario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('father_article', models.ForeignKey(help_text='articulo donde esta el comentario', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article')),
                ('father_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
            ],
        ),
    ]
